version: "2"
services:
  pipot-base:
    container_name: pipot-base
    restart: "no"
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo-pot
    environment:
      PORT: 3000
      MONGODB_URI: "mongodb://mongo-pot/pipot"
  mongo-pot:
    container_name: mongo-pot
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - volumedb:/data/db
volumes: 
  volumedb: